# decaysim
# Parameters and settings

[params]

tau_seed = 0.19745 # in [s]

timestep = 0.01048  # in [s]
n_sim_steps = 153 # approx. 1.6 s total time after injection

n_sim = 151  # 32 number of simulated decays in setting 1
n_trials = 1000

n_decay_steps = 0  # either 0 or 1

mean_ion = 9.44e-7
stdv_ion = 7.7408e-8 # MEAN_ION * 0.082

mean_bkgnd = 5.44e-7
stdv_bkgnd = 2.06e-8 # MEAN_BKGND * 0.038

empty_shots = false
empty_shots_probability = 0.0


[settings]

tasks = ['addup', 'mle'] # Tasks: what to simulate, like 'addup', 'distro', 'mle'
output_path = "./out_mo"
plot_every_event = false # expect longer simulation times if set to true. applies only to addup method
save_npz = true
plot_titles = false # turn plot titles on or off
